# Generated by Django 2.2.6 on 2019-10-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='China', max_length=40),
        ),
    ]
