# Generated by Django 2.2.6 on 2019-10-23 03:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_customer_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('country', models.CharField(default='China', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.CharField(default='comment here', max_length=1000)),
                ('commodity', models.ManyToManyField(to='order.Commodity')),
                ('custom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
    ]
